name: x5_webview_example
description: Demonstrates how to use the x5_webview plugin.
publish_to: 'none'

version: 0.3.3+33

environment:
  sdk: ">=3.1.0 <4.0.0"

dependency_overrides:
  file: 7.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  dio: ^5.3.2
  webview_flutter: ^4.2.3
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  x5_webview:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

